name: CI Pipeline

on:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'

jobs:
    common:
        runs-on: ubuntu-latest
        outputs:
            tags: ${{ steps.meta.outputs.tags }}
        steps:
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/enymawse/psps
                      enymawse/psps
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=sha

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

    rolling:
        needs: common
        runs-on: ubuntu-latest
        if: github.ref_name == 'main'
        steps:
            - name: Build and push rolling
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      ghcr.io/enymawse/psps:rolling
                      enymawse/psps:rolling

    versioned:
        needs: common
        runs-on: ubuntu-latest
        if: startsWith(github.ref_name, 'v')
        steps:
            - name: Build and push versioned
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      ${{ needs.common.outputs.tags }}
