name: psps ci

on:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/enymawse/psps
                      enymawse/psps
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=sha

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      ghcr.io/enymawse/psps:${{ github.ref_name == 'main' && 'rolling' || steps.meta.outputs.tags }}
                      enymawse/psps:${{ github.ref_name == 'main' && 'rolling' || steps.meta.outputs.tags }}
