name: Docker Login

on:
    workflow_call:
        inputs:
            ghcr:
                required: true
                type: boolean
            dockerhub:
                required: true
                type: boolean

jobs:
    login:
        runs-on: ubuntu-latest
        steps:
            - name: Login to GHCR
              if: inputs.ghcr == true
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to Docker Hub
              if: inputs.dockerhub == true
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
